### PR TITLE
old increment not enough,this change increment to factorial

### PR DESCRIPTION
**Pull request by 286897655**
old increment not enough.

### CODE REVIEW

**Comment by ChuckRenner** [comment]
Can one of the admins verify this patch?

**Comment by mitza-oci** [comment]
Thanks for contributing a pull request.  Please take a look at the following issues:

- See our coding guidelines in the repository at docs/html/guidelines/guidelines.html
- Travis errors https://travis-ci.org/objectcomputing/OpenDDS/jobs/219155778
- These seem to be unrelated changes, please make distinct pull requests for them

**Comment by ChuckRenner** [comment]
Can one of the admins verify this patch?

**Comment by 286897655** [comment]
i should learn how make a pull request~~~~

**Pull request closed without merging**
