### PR TITLE
Use gcc8 as default and add clang6 as new compiler, gcc5/6 and clang5…

### PR DESCRIPTION
**Pull request by jwillemsen**
… as different configurations

    * .travis.yml:

### CODE REVIEW

**Comment by mitza-oci** [comment]
I see what it's complaining about with safety profile + GCC 8.  That's a combo we haven't tried yet.

In PoolAllocator.h (with safety profile enabled), there's a assumption that lexically putting the keyword `const` next to the key type produces the correct value type.  That's not correct when `K` is a pointer.

I think the right way to handle it is to write the equivalent of C++11's `std::add_const` metafunction (1-liner) and use it here.

**Comment by mitza-oci** [comment]
Safety profile build will work once #869 is merged.

**Comment by mitza-oci** [comment]
@jwillemsen please merge master to your branch, seems like there's no simple way to get travis to build the new merge commit on its own

**Comment by jwillemsen** [comment]
@mitza-oci Master has been merged

**Comment by mitza-oci** [comment]
The builds on Travis's matrix that are just configured as COMPILER=X are taking a long time.  We may need to add other options to those lines to keep them within the time limit.

**Pull request merged**
