### PR TITLE
Add missing virtual

### PR DESCRIPTION
**Pull request by jwillemsen**
* dds/DCPS/TopicImpl.h:

### CODE REVIEW

**Review by iguessthislldo — COMMENTED** [review]
It's not "missing". It's not necessary in inherited virtual methods.

**Comment by jwillemsen** [comment]
But it will make it clear they are virtual, with C++11 I would have added override

**Comment by jwillemsen** [comment]
All other overridden methods in this class do use virtual

**Comment by sonndinh** [comment]
> All other overridden methods in this class do use virtual

I don't think adding `virtual` makes it clear that the function is overridden because a `virtual` member function doesn't mean it overrides a member from its base classes. Maybe we could go the other way, that is remove `virtual` from functions that won't be overridden.

**Comment by mitza-oci** [comment]
I guess it's not explicitly in the style guide, but we have not been adding `virtual` to these.

**Pull request closed without merging**
