### PR TITLE
Add OpenDDS to the cmake project name to make clear these are OpenDDS…

### PR DESCRIPTION
**Pull request by jwillemsen**
… projects

    * tests/cmake_integration/Messenger/Messenger_1/CMakeLists.txt:
    * tests/cmake_integration/Messenger/Messenger_2/CMakeLists.txt:
    * tests/cmake_integration/README.md:

### CODE REVIEW

**Comment by jwillemsen** [comment]
Prevents duplicate project names within a ROS2 tree

**Comment by mitza-oci** [comment]
I'm not opposed to the change but I can't say I understand why it would be needed.  These are just examples of using the CMake support, they aren't intended to be part of any other workspace.

**Comment by jwillemsen** [comment]
When checking out opendds as part of ros2 the ros2 tooling complained about the duplicate project name

**Comment by mitza-oci** [comment]
So it finds and uses all `CMakeLists.txt` recursively without a way to exclude anything?  If using submodules you'll also have the rapidjson and gtest ones.  Where can we file an issue on "ros2 tooling"?

**Comment by jwillemsen** [comment]
I took the easy approach, still learning ros2

**Comment by mitza-oci** [comment]
Please add a link to the GitHub repo of the ros2 tool that's doing this.

**Comment by jwillemsen** [comment]
Probably the colcon ros2 tooling has this limitation

**Comment by mitza-oci** [comment]
According to https://index.ros.org/doc/ros2/Linux-Development-Setup/#build-the-code-in-the-workspace, AMENT_IGNORE may be used for this.

**Comment by jwillemsen** [comment]
Yes, I am using that for testing but would it cause any harm to just let OpenDDS provide unique project names within its own tree for simplicity?

**Comment by mitza-oci** [comment]
Like I was saying before, I don't think it's simpler to change upstream code in unexpected ways to satisfy some odd downstream requirement.  There will be other CMakeLists.txt files in the source tree if submodules are used, and it's possible that more of this kind of thing will be added in the future.

**Pull request merged**
