### PR TITLE
XTypes: Fix Deadlock in Type Lookup Service

### PR DESCRIPTION
**Pull request by iguessthislldo**

### CODE REVIEW

**Comment by iguessthislldo** [comment]
@mitza-oci @jrw972 Is there a way to assert the ACE lock is held like [std::unique_lock<Mutex>::owns_lock](https://en.cppreference.com/w/cpp/thread/unique_lock/owns_lock)?

**Review by kuznetsovmoci — APPROVED** [review]

**Comment by mitza-oci** [comment]
> 
> 
> @mitza-oci @jrw972 Is there a way to assert the ACE lock is held like [std::unique_lock::owns_lock](https://en.cppreference.com/w/cpp/thread/unique_lock/owns_lock)?

`ACE_Guard::locked` ?

**Comment by iguessthislldo** [comment]
The guard I would be interested is in another function way down in the stack. I might also be thinking about this wrong.

**Comment by mitza-oci** [comment]
> The guard I would be interested is in another function way down in the stack. I might also be thinking about this wrong.

`ACE_Thread_Mutex::tryacquire`

**Review by mitza-oci — APPROVED** [review]

**Pull request merged**
