### PR TITLE
Test extension and fix for using query conditions on keyed data

### PR DESCRIPTION
**Pull request by jwillemsen**
Test extension and fix for using query conditions together with keyed_data and using dispose, see issue #550 and #581

### CODE REVIEW

**Comment by jwillemsen** [comment]
Some tests are now failing because with NOT_ALIVE_DISPOSED_INSTANCE_STATE we could get valid_data at the moment there are keys used. Before updating these few tests we first have to decide whether the idea of the change (to keep the received data with a dispose so that we can apply a filter) is the direction to go

**Comment by mitza-oci** [comment]
I cancelled the Jenkins build on this one.  Need time on the server for other PRs which are nearly ready to merge.

**Comment by mitza-oci** [comment]
We do want the ability to query the disposed data.  However, to maintain some safety we should check if the query refers to any non-key fields.  Such queries would not mach any disposed data samples (current behavior).

**Comment by mitza-oci** [comment]
See PR #900

**Pull request closed without merging**
