### PR TITLE
According to the azure pipelines github repo perl should be in the pa…

### PR DESCRIPTION
**Pull request by jwillemsen**
…th on vs2017

### CODE REVIEW

**Comment by jwillemsen** [comment]
See https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Validate-Perl.ps1

**Comment by jwillemsen** [comment]
Ok, looks there is a perl but it seems one the configure script doesn't support yet
```
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\aa02a820-cb01-4190-9c92-7d918ab219c5.cmd""
ERROR: unknown host msys, stopped at configure line 348.
Options:
```

**Comment by mitza-oci** [comment]
There is some Perl but not a Windows Perl (ActiveState, Strawberry, etc.).  I don't think we're going to support MSys since that's a very specialized use case.

**Comment by jwillemsen** [comment]
Looking at https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-Perl.ps1 I would expect it to be strawberry perl but it seems it is something different

**Comment by mitza-oci** [comment]
I tried this when I was setting up azure-pipelines.yml.  I even looked into supporting msys but it uses nonstandard paths.  Seems like a bug in azure's image or their docs.

**Comment by jwillemsen** [comment]
Let us retry when they ship a new image to azure

**Comment by mitza-oci** [comment]
Should this be an issue in the Azure CI repo?

**Comment by jwillemsen** [comment]
Yes, we should report it there also

**Comment by mitza-oci** [comment]
Is there an issue we can link to?

**Comment by jwillemsen** [comment]
Reported this upstream as https://github.com/Microsoft/azure-pipelines-image-generation/issues/822

**Pull request closed without merging**
