### PR TITLE
Use a macro to switch between std::auto_ptr and std::unique_ptr based…

### PR DESCRIPTION
**Pull request by ocielliottc**
… on the ACE_HAS_CPP11 macro

### CODE REVIEW

**Comment by mitza-oci** [comment]
"This code was generated by the XML Schema Compiler" https://github.com/DOCGroup/XSC

**Comment by ocielliottc** [comment]
Ah, I guess I could have read the header comment.  Thanks.

**Comment by jwillemsen** [comment]
XSC has a C++11 generation mode but that generates code which will only work with C++11. Maybe just extend XSC with a similar macro for the regular generation which works with C++03

**Comment by mitza-oci** [comment]
> XSC has a C++11 generation mode but that generates code which will only work with C++11. Maybe just extend XSC with a similar macro for the regular generation which works with C++03

Or, since qos_xml is an optional feature, we could have it only build when C++11 is available.

**Comment by mitza-oci** [comment]
Should this be closed because of #1181?

**Comment by ocielliottc** [comment]
Yes, it should.

**Pull request closed without merging**
