### PR TITLE
Use ACE_OS::chdir instead of native windows call

### PR DESCRIPTION
**Pull request by jwillemsen**
* dds/DCPS/FileSystemStorage.cpp:

### CODE REVIEW

**Comment by mitza-oci** [comment]
I need to do some more research to see why we have it this way.  It is using the special `\\?\` prefix on Windows to avoid path length limits.  That may not have been compatible with the way ACE has it.  ACE also seems to be doing a wide-to-narrow conversion when wchar is enabled.

**Comment by jwillemsen** [comment]
At the moment wchar is enabled there is wchar_t version which does exactly the same as OpenDDS used, see https://github.com/DOCGroup/ACE_TAO/blob/df4927c9dd70cd32aab0ea2e35a21d726e827c4e/ACE/ace/OS_NS_unistd.inl#L144

**Comment by mitza-oci** [comment]
> At the moment wchar is enabled there is wchar_t version which does exactly the same as OpenDDS used, see https://github.com/DOCGroup/ACE_TAO/blob/df4927c9dd70cd32aab0ea2e35a21d726e827c4e/ACE/ace/OS_NS_unistd.inl#L144

Sorry, my previous comment wasn't correct.  It's when wchar is *not* enabled.

**Comment by mitza-oci** [comment]
Replaced by #2791

**Pull request closed without merging**
