### PR TITLE
Removed _var_ptr/_ptr_type from the generated type support implementa…

### PR DESCRIPTION
**Pull request by jwillemsen**
…tion, we can get these from the base, also remove _narrow, also usable from the IDL generated stub

    * dds/idl/ts_generator.cpp:

### CODE REVIEW

**Comment by mitza-oci** [comment]
The code you removed is there for a reason.
```
error C2385: ambiguous access of '_var_type'
 note: could be the '_var_type' in base 'OpenDDS::DCPS::LocalObject<Messenger::MessageTypeSupport>'
 note: or could be the '_var_type' in base 'OpenDDS::DCPS::LocalObject<OpenDDS::DCPS::TypeSupport>'
```

But this illustrates that we need some test "coverage" of this compile-time ability.

**Comment by jwillemsen** [comment]
According to the comment in LocalObject.h that template is there to resolve ambiguity, doesn't that work? Isn't it very risky to allow to use objects on the stack, they could be gone at the moment we get delayed callbacks.

**Comment by mitza-oci** [comment]
re: Comment in LocalObject, I believe that works for single inheritance but in this case we have TypeSupportImpl which has it's own definition of these members.

re: on the stack, I don't see that being relevant here.  I took a test that used listeners normally and had it use the _var_type typedef instead (as one might do when writing code in a template), with your change it failed (see earlier comment).

**Comment by jwillemsen** [comment]
I can add the _var_type/_ptr_type back again, what about narrow, also required?

**Comment by mitza-oci** [comment]
I believe those all work the same way, it's just class member lookup with multiple inheritance.  I think we should just close this PR, I don't see anything changing here.

**Pull request closed without merging**
