### PR TITLE
GitHub Actions: use a newer vcpkg

### PR DESCRIPTION
**Pull request by mitza-oci**
vcpkg installs Qt5 and its dependencies which wireshark needs
older vcpkg uses a bad download URL for PCRE

### CODE REVIEW

**Comment by ClaytonCalabrese** [comment]
Do we want to change this for all of the vcpkgGitCommitId or just this one?

**Comment by mitza-oci** [comment]
> 
> 
> Do we want to change this for all of the vcpkgGitCommitId or just this one?

If it works for wireshark we could try changing it for the others.

**Review by ClaytonCalabrese — APPROVED** [review]

**Comment by jwillemsen** [comment]
When this works, can you also make a PR to upgrade vcpkg for ACE/TAO/MPC? That way we build everything with the same version

**Comment by mitza-oci** [comment]
pcre2 is still broken in vcpkg, waiting for https://github.com/microsoft/vcpkg/pull/21248 to be merged

**Pull request merged**
