### PR TITLE
Upgrade to lukka/run-vcpkg@v7

### PR DESCRIPTION
**Pull request by jwillemsen**
* .github/workflows/build_and_test.yml:

### CODE REVIEW

**Comment by simpsont-oci** [comment]
I looks like one of the actual builds failed because the image ran out of disk space. Not sure if this is entirely the fault of run-vcpkg 7, but we'll probably wait to upgrade until we're done with our next round of Github Actions changes.

**Comment by mitza-oci** [comment]
> 
> 
> It looks like one of the actual builds failed because the image ran out of disk space. Not sure if this is entirely the fault of run-vcpkg 7, but we'll probably wait to upgrade until we're done with our next round of Github Actions changes.

We'll attempt merging this after #2451

**Comment by mitza-oci** [comment]
@jwillemsen merge conflict on this one

**Comment by jwillemsen** [comment]
Looks easier to just recreate this later

**Pull request closed without merging**
