### PR TITLE
add TAB minutes from 3-7-22 meeting

### PR DESCRIPTION
**Pull request by kroegerk**
@mitza-oci

### CODE REVIEW

**Comment by iguessthislldo** [comment]
There seems to be an inconsistency with the HTML.

**Comment by kroegerk** [comment]
Shoot. Thanks, @iguessthislldo . I'll take a look at it.

**Comment by kroegerk** [comment]
@iguessthislldo , sorry about that. See if it will merge now.

**Comment by iguessthislldo** [comment]
Sorry I should have taken a closer look at this. It's not your file, it's something wrong in the template generating the "Minutes Archive" box that is on this page https://opendds.org/foundation/minutes/ and other minutes pages.

**Comment by kroegerk** [comment]
Oh. :-|

I hope you know how to fix that, 'cause I have no clue!

**Comment by iguessthislldo** [comment]
> I hope you know how to fix that, 'cause I have no clue!

Fortunately it was pretty simple, the fix is in #3556. The cause was a misplaced line that was going cause a problem when a minutes page for a another year was added. I tested it by adding this new page locally and generating the site and it looks good.

@mitza-oci We should merge my PR first, and then this one.

**Pull request merged**
