### PR TITLE
Change Ubuntu 18 builds to Ubuntu 22

### PR DESCRIPTION
**Pull request by jrw972**

### CODE REVIEW

**Review by simpsont-oci — APPROVED** [review]

**Review by mitza-oci — CHANGES_REQUESTED** [review]
There are new warnings from Qt's headers in build_u22_stat_qt_ws_sec.  In the past we've used a #pragma to take care of these.

**Comment by jrw972** [comment]
> There are new warnings from Qt's headers in build_u22_stat_qt_ws_sec. In the past we've used a #pragma to take care of these.

Do you have an example?

**Comment by mitza-oci** [comment]
> > There are new warnings from Qt's headers in build_u22_stat_qt_ws_sec. In the past we've used a #pragma to take care of these.
> 
> Do you have an example?

https://github.com/objectcomputing/OpenDDS/pull/3622/files#annotation_4111267126

**Review by iguessthislldo — APPROVED** [review]
Assuming the warnings get fixed

**Pull request merged**
