### PR TITLE
Fixed function to call in lines 119:120

### PR DESCRIPTION
**Pull request by AndroidDev77**

### CODE REVIEW

**Comment by AndroidDev77** [comment]
@AndroidDev77 	Fixed function to call in lines 119:120

**Comment by mitza-oci** [comment]
I don't understand why this change is proposed.  Could you provide more background info?

I've seen very few scenarios where I would recommend mpc.pl over mwc.pl.  In the MPC documentation, it says "The most common way to use the Make Project Creator is to run the workspace generator (mwc.pl)."

**Comment by iamtheschmitzer** [comment]
Did you run into an issue running mwc.pl?

**Comment by AndroidDev77** [comment]
You must create a workspace first. The instructions only says to create a
project file. If you run mwc with no workspace file it errs out telling you
that you have no workspace.

**Comment by mitza-oci** [comment]
Every directory in the filesystem is an mpc workspace.  The default workspace is the current directory, which contains an *.mpc file that's the (only) member of the workspace.

**Comment by mitza-oci** [comment]
I would like to try running this myself to make sure the directions are correct.  AndroidDev77, please specify which platform you're building on and version numbers of the C++ compiler and JDK.

**Pull request closed without merging**
