### PR TITLE
RTPS/SPDP: Add new config option SpdpLocalAddress for configuration of the…

### PR DESCRIPTION
**Pull request by nxdefiant**
Add new  rtps_discovery option SpdpLocalAddress for configuration of the SPDP Interface. Default to DCPSDefaultAddress (section common) if set.

### CODE REVIEW

**Comment by ChuckRenner** [comment]
Can one of the admins verify this patch?

**Comment by mitza-oci** [comment]
ok to test

**Comment by mitza-oci** [comment]
Please try this test on your local build:
cd tests/DCPS/DCPSInfoRepo
./run_test.pl rtps_disc

Our Jenkins build of this PR encountered the following error in that test:
`(4926|140245144123264) Spdp::SpdpTransport::open_unicast_socket() - failed setting unicast local_addr to port 9660 ACE_INET_Addr::set: Unknown error -2
(4926|140245144123264) RtpsDiscovery::add_domain_participant() - failed to initialize RTPS Simple Participant Discovery Protocol: failed to set unicast local address
`

**Comment by nxdefiant** [comment]
ok, I did not expect Spdp to be used without RTPS, is there an easy way to run all tests?

**Comment by mitza-oci** [comment]
In case you haven't dug in to find it, Travis is showing "Error: ./dds/DCPS/RTPS/Spdp.cpp:740: found trailing whitespace"

Our local CI builds run all tests using "bin/auto_run_tests.pl -Config RTPS"

**Comment by nxdefiant** [comment]
Test finally pass on my linux box.

**Pull request merged**
