### PR TITLE
Check if item_registered_data_ is not null before calling into the…

### PR DESCRIPTION
**Pull request by jwillemsen**
…aluator, see issue #495

    * dds/DCPS/DataReaderImpl_T.h:

### CODE REVIEW

**Comment by mitza-oci** [comment]
Please add a regression test.

**Comment by jwillemsen** [comment]
@mitza-oci Hopefully soon we can use dds4ccm as unit test, see the issue we made for the callstack of the crash we got.

**Comment by mitza-oci** [comment]
Is there some test in CIAO we could use to reproduce the problem?  The callstack isn't enough to learn what application code puts OpenDDS in this failure state.  (I assume this is the same for PR #490 so I'm not going to replicate my comment there.)

**Comment by jwillemsen** [comment]
This is related to issue #495, which is triggered by an AXCIOMA DDS4CCM unit test. Looks CIAO/connectors/dds4ccm/tests/QueryCondition/EventListener is a little bit comparable with the AXCIOMA version but that seems to run

**Comment by jwillemsen** [comment]
Looks related to filter and unregistering keyed samples

**Pull request merged**
