### PR TITLE
Consolidated IDL files from multiple tests

### PR DESCRIPTION
**Pull request by mitza-oci**
Variation of #1211 that leaves `tests/DCPS/Messenger` as its own standalone directory.

### CODE REVIEW

**Comment by iguessthislldo** [comment]
I though messenger was being left alone, now I see it isn't. Why does #1211 have a separate library?

**Comment by mitza-oci** [comment]
> 
> 
> I though messenger was being left alone, now I see it isn't. Why does #1211 have a separate library?

Not sure what you're asking about.  There is now common code instead of individual files in `tests/DCPS/{BuiltInTopicTest,Deadline,DPFactoryQos,...}`.

**Comment by iguessthislldo** [comment]
I'm asking why have the Consolidated Messenger Library at all and not just link to DDS_Messenger_Idl?

**Comment by mitza-oci** [comment]
> 
> 
> I'm asking why have the Consolidated Messenger Library at all and not just link to DDS_Messenger_Idl?

I suppose only @simpsont-oci can answer that directly, but I think it makes sense to have it be its own directory so that if a maintainer needs to change it, they know that the change will impact the whole group of tests that share the IDL.

**Pull request merged**
