### PR TITLE
Visual Studio 2017 also needs /bigobj

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by mitza-oci** [comment]
Do you have an automated build for Visual C++ 2017?

**Comment by jwillemsen** [comment]
We have a first build, the missing of /bigobj made was visible there

**Comment by jwillemsen** [comment]
With these changes msvc15 now compiles error free. Added a new build to the scoreboard which compiles master, that currently fails

**Comment by jwillemsen** [comment]
Build with master results is now available online at http://buildlogs.remedy.nl/win_msvc15_opendds_debug/index.html

**Comment by mitza-oci** [comment]
There are changes in this PR that have nothing to do with VS2017, please separate those out.

**Comment by jwillemsen** [comment]
#481 has the test changes

**Pull request closed without merging**
