### PR TITLE
Use a scope to release the guard, much safer than manually releasing …

### PR DESCRIPTION
**Pull request by jwillemsen**
…the guard. Also reduce the number of exit points

    * dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp:

### CODE REVIEW

**Comment by mitza-oci** [comment]
I think the limited use of ``guard.release()`` is OK when it's just for the last action in the method.  It avoids unnecessarily complicating the method.  Same for single-exit-point style, it's unnecessarily complicating things.

**Comment by jwillemsen** [comment]
Also the guard is safer in case exceptions occur

**Comment by jwillemsen** [comment]
What about the risk of exceptions? Isn't the scope making sure that we always release the lock?

**Comment by mitza-oci** [comment]
The general structure of these methods is:
```
void foo()
{
  Guard g(lock);
  action1();
  g.release();
  action2();
}
```
Where action1 requires the lock and action2 must be called without the lock.  What is the "risk of exceptions" here?  If action1 throws, the lock is released due to g's destructor.  If action2 throws, the lock is already released by design.

**Pull request closed without merging**
