### PR TITLE
Add requires for googletest, makes it possible to disable the compila…

### PR DESCRIPTION
**Pull request by jwillemsen**
…tion of all tests dependent on googletest using googletest=0 through default.features

    * MPC/config/googletest.mpb:

### CODE REVIEW

**Comment by jwillemsen** [comment]
Makes it possible to disable googletest as dependent library because of https://github.com/objectcomputing/OpenDDS/issues/2167

**Comment by jwillemsen** [comment]
MPC features are default 1 so this will not impact the default case

**Comment by mitza-oci** [comment]
As of now GoogleTest is a requirement when building with tests enabled.  This is documented in docs/dependencies.md.

This risk of changing it is that there would be different subsets of testing.  This is not desirable.

GoogleTest doesn't buy us all that much since we are not using advanced features.  What it does can be done with a simple assertion macro.  If GoogleTest is too onerous a requirement then it should be completely removed.

**Comment by simpsont-oci** [comment]
I'm pretty sure the security access control tests use google mock.

**Comment by jwillemsen** [comment]
I disabled OpenDDS security for RHEL 7.5 because of the problems compiling google test there, looks only DCPS/tests/SequenceIteratorTest.cpp uses google test, looks that one can be easily rewritten to not use googletest

**Comment by mitza-oci** [comment]
> I disabled OpenDDS security for RHEL 7.5 because of the problems compiling google test there, looks only DCPS/tests/SequenceIteratorTest.cpp uses google test, looks that one can be easily rewritten to not use googletest

Google Test can be built on RHEL 7.5 with a modern CMake version.  I just did it myself yesterday.

**Comment by jwillemsen** [comment]
Reworked unit test in #2195. Did you build cmake from sources or used a specific RHEL channel?

**Comment by mitza-oci** [comment]
> Reworked unit test in #2195. Did you build cmake from sources or used a specific RHEL channel?

I downloaded CMake from the link that cmake.org provided, which I think goes to GitHub

**Comment by jwillemsen** [comment]
> > Reworked unit test in #2195. Did you build cmake from sources or used a specific RHEL channel?
> 
> I downloaded CMake from the link that cmake.org provided, which I think goes to GitHub

Ok, a manual build from sources, something I can't do on some of our build slaves. Hopefully at the moment we need DDS security support we are at RHEL8 which has much more modern support for various dev tools

**Comment by mitza-oci** [comment]
> > > Reworked unit test in #2195. Did you build cmake from sources or used a specific RHEL channel?
> > 
> > 
> > I downloaded CMake from the link that cmake.org provided, which I think goes to GitHub
> 
> Ok, a manual build from sources, something I can't do on some of our build slaves. Hopefully at the moment we need DDS security support we are at RHEL8 which has much more modern support for various dev tools

No, it was a download of a Linux binary.

**Comment by jwillemsen** [comment]
> > > > Reworked unit test in #2195. Did you build cmake from sources or used a specific RHEL channel?
> > > 
> > > 
> > > I downloaded CMake from the link that cmake.org provided, which I think goes to GitHub
> > 
> > 
> > Ok, a manual build from sources, something I can't do on some of our build slaves. Hopefully at the moment we need DDS security support we are at RHEL8 which has much more modern support for various dev tools
> 
> No, it was a download of a Linux binary.

Ok, I will try to find some time to try to install that as part of the job into a local user directory in case we build opendds with security enabled.

**Comment by mitza-oci** [comment]
It's just a wget of `https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-Linux-x86_64.tar.gz`, untar, and run cmake using an absolute path

**Comment by iguessthislldo** [comment]
> GoogleTest doesn't buy us all that much since we are not using advanced features. What it does can be done with a simple assertion macro. If GoogleTest is too onerous a requirement then it should be completely removed.

The XTypes tests make extensive use of Google Test. It would not be simple to remove.

**Comment by jwillemsen** [comment]
> It's just a wget of `https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-Linux-x86_64.tar.gz`, untar, and run cmake using an absolute path

Next build of our rhel75 opendds build installs cmake 3.19.1 and uses that for googletest

**Comment by jwillemsen** [comment]
cmake 3.19 gives the following warnings on googletest, latest versions of googletest do require C++11 so upgrading googletest is not an option right now, something for OpenDDS 4.0. A downgrade to cmake 3.18.5 gets rid of these warnings, so we are using 3.18.5 for the moment

```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
```

**Pull request closed without merging**
