### PR TITLE
Add dependabot configuration for github actions

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by mitza-oci** [comment]
What does it do?

**Comment by jwillemsen** [comment]
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot

**Comment by jwillemsen** [comment]
See for example https://github.com/jwillemsen/saj_collector/pull/14, dependabot will create a PR when a github action that is used is not the most recent

**Review by simpsont-oci — APPROVED** [review]

**Comment by jwillemsen** [comment]
@mitza-oci can you check whether dependabot is enabled, see https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Pull request merged**
