### PR TITLE
Update googletest submodule to a commit on their 1.8.x branch after 1.8.1

### PR DESCRIPTION
**Pull request by mitza-oci**
1.8.1 doesn't compile on CentOS/RHEL 6
https://github.com/google/googletest/pull/2085

### CODE REVIEW

**Comment by jwillemsen** [comment]
Looks googletest/mock now install in a lib64 directory on Linux 64bit, the MPC files don't handle that

```
-- Installing: /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/tests/googletest/build/install/lib64/libgmock.a
-- Installing: /home/build/jenkins/workspace/fc_opendds_versioned/BUILD/DOC_ROOT/DDS/tests/googletest/build/install/lib64/libgmock_main.a
```

**Comment by mitza-oci** [comment]
@jwillemsen CI build didn't have that problem.  What is required to reproduce it?
```
 Installing: /home/vsts/work/1/s/tests/googletest/build/install/lib/libgtest.a
```

**Comment by jwillemsen** [comment]
Is on our latest build on fc30, see http://buildlogs.remedy.nl/fc_opendds_versioned.

**Comment by mitza-oci** [comment]
So that's using the 1.8.1 release tag, but it shouldn't be any different with the newer revision.  Probably a Fedora difference since they have `/usr/lib64` for system libraries.  I'll look into it.

**Comment by jwillemsen** [comment]
Also on my OpenSuSE tumbleweed system it uses lib64

```
-- Installing: /home/johnny/ACE/OpenDDS/tests/googletest/install/lib64/libgmock.a
-- Installing: /home/johnny/ACE/OpenDDS/tests/googletest/install/lib64/libgmock_main.a
-- Installing: /home/johnny/ACE/OpenDDS/tests/googletest/install/lib64/pkgconfig/gmock.pc
-- Installing: /home/johnny/ACE/OpenDDS/tests/googletest/install/lib64/pkgconfig/gmock_main.pc
```

**Comment by mitza-oci** [comment]
Looks like it can be fixed with `-DCMAKE_INSTALL_LIBDIR=lib`

**Comment by jwillemsen** [comment]
> Looks like it can be fixed with `-DCMAKE_INSTALL_LIBDIR=lib`

Add that to our linux builds and restarted them

**Comment by jwillemsen** [comment]
Something to document and also add to the configure script?

**Comment by mitza-oci** [comment]
Yes, I'll add it to `configure`.

**Pull request merged**
