### PR TITLE
Removed dependency from googletest for NetworkConfig test

### PR DESCRIPTION
**Pull request by jwillemsen**
* tests/DCPS/UnitTests/NetworkConfig.cpp:
    * tests/DCPS/UnitTests/UnitTests.mpc:

### CODE REVIEW

**Comment by sonndinh** [comment]
What is the reason for removing googletest for this test?

**Comment by jwillemsen** [comment]
#2167, why use googletest for just calling 4 operations in a main?

**Comment by iguessthislldo** [comment]
> #2167 

That issue is closed and this specific test isn't mentioned in that issue.

**Comment by sonndinh** [comment]
> #2167, why use googletest for just calling 4 operations in a main?

If the removal is because of the CMake build error for gtest in #2167, I think Adam mentioned the latest CMake works for him.

**Comment by iguessthislldo** [comment]
Closing because of #2167

**Pull request closed without merging**
