### PR TITLE
Fixed crashes as reported with issue #489

### PR DESCRIPTION
**Pull request by jwillemsen**
Need to check instance before using it, during testing we had some runs where instance was nil causing a crash

### CODE REVIEW

**Comment by mitza-oci** [comment]
Please add a regression test.

**Comment by jwillemsen** [comment]
@mitza-oci Hopefully soon we can use dds4ccm as unit test, see the issue we made for the callstack of the crash we got.

**Comment by jwillemsen** [comment]
This is also AXCIOMA DDS4CCM, comparable with CIAO/connectors/dds4ccm/tests/QueryCondition/Different/descriptors/run_test.pl

**Comment by jwillemsen** [comment]
Added full logs to the issue

**Comment by jwillemsen** [comment]
Have a plain OpenDDS reproducer at https://github.com/jwillemsen/OpenDDS/tree/jwi-samplelost

**Pull request merged**
