### PR TITLE
Don't use sudo anymore and use travis_latest as group

### PR DESCRIPTION
**Pull request by jwillemsen**
as described in https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

### CODE REVIEW

**Comment by jwillemsen** [comment]
Looks travis is taking longer and longer, maybe reduce what we build there and increase what we build on Azure DevOps, there is no limit there

**Comment by mitza-oci** [comment]
I agree that with Azure Pipelines offering multi-platform support without time limits we can de-emphasize Travis as we keep migrating build configurations to Azure.

For this PR in particular, why do we want `travis_latest` instead of LTS?

**Comment by jwillemsen** [comment]
Changed it just to travis_latest because we do it in more projects, just use the latest version for CI.

**Comment by jwillemsen** [comment]
On azure multiple gcc versions works, only haven't had time to try to add clang

**Pull request merged**
