### PR TITLE
At the moment the users calls delete_datawriter/delete_datareader it …

### PR DESCRIPTION
**Pull request by jwillemsen**
…can happen the DDS entity is deleted for the user but the underlying object still exists due to reference counting. As first step in the cleanup now set the listener to nil so that we don't callback onto the listener after the user has called delete on the DR/DW, see issue #654

    * dds/DCPS/DataReaderImpl.cpp:
    * dds/DCPS/DataWriterImpl.cpp:

### CODE REVIEW

**Comment by jwillemsen** [comment]
@mitza-oci In the OCI build the test `tests/DCPS/Reconnect/run_test.pl bp_timeout` fails. As far as I can determine this test incorrectly assumes that a listener is invoked after the DW has been deleted. Adam, any suggestions?

**Comment by jwillemsen** [comment]
On master I see in our build also a failure for `tests/DCPS/Reconnect/run_test.pl restart_sub`

**Comment by mitza-oci** [comment]
Let's focus on just `tests/DCPS/Reconnect/run_test.pl bp_timeout` for now (not restart_sub), since it seems to fail consistently on this branch.  I don't know that it is assuming a listener is called after DW is deleted.  It does want the listener to be invoked at some point.  If it is deleting the DW too early, could that be fixed by changing when the subscribing program declares itself finished via subscriber_finished.txt?

**Comment by jwillemsen** [comment]
The subscriber program does use that file

**Comment by mitza-oci** [comment]
retest this please
(starting Jenkins build)

**Pull request merged**
