### PR TITLE
Azure Pipelines: Adding Messenger tests for all Visual Studio builds

### PR DESCRIPTION
**Pull request by kuznetsovmoci**

### CODE REVIEW

**Comment by mitza-oci** [comment]
Since vcpkg broke VS2015 (again), should we make that a non-security build?

**Comment by jwillemsen** [comment]
Be aware that vs2015 support on azure will be removed coming March, see https://github.com/DOCGroup/ACE_TAO/issues/1033

**Comment by mitza-oci** [comment]
Script step to generate sln files (make this conditional so it only runs for Release)
```
mwc.pl -type [vs2019|other] tests\DCPS\Messenger DevGuideExamples\DCPS\Messenger
```
Step to build: use VSBuild task pointing to the new sln files in the `solution:` argument

**Comment by mitza-oci** [comment]
In order to make the VS2015 build pass, remove the vcpkg steps from that section.
Also change the VS2017 section to be the same as VS2019.

**Comment by mitza-oci** [comment]
I'm cancelling this run on Azure Pipelines so that other PRs have time to build.  We will need further changes here anyway.  As I was saying before, I recommend "prototyping" these changes in your own forked repo until they're ready.

**Pull request merged**
