### PR TITLE
Removed unused third-party services from README.md

### PR DESCRIPTION
**Pull request by mitza-oci**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Coday is still enabled as far as I can tell

**Comment by mitza-oci** [comment]
> 
> 
> Codacy is still enabled as far as I can tell

It doesn't result in "checks" appearing in the pull requests.  So we don't know if each change to the repository is impacting whatever it is that Codacy is doing.

**Comment by jwillemsen** [comment]
Maybe that is a permission issue in the project settings?

**Review by ClaytonCalabrese — APPROVED** [review]

**Comment by mitza-oci** [comment]
> 
> 
> Maybe that is a permission issue in the project settings?

Is it working in ACE_TAO or some other repository we can use as an example?

**Pull request merged**
